function run_tests()

env_size = 30;
step_count = 150;
plot_control = 0;
quick_stop = false;
img_output = true;

agents = [...
    36 0 4;...
    30 6 4;...
    24 12 4;...
    18 18 4;...
    12 24 4;...
    6 30 4;...
    0 36 4];

% disease = [0; 0.25; 0.5; 0.75;];
% disease = [0; 0.5; 1;];
disease = [0];%; 0.5; 1;];


for i = 1:size(agents)
    vuln_count = agents(i, 1);
    vacc_count = agents(i, 2);
    infec_count = agents(i, 3);
    
    for j = 1:size(disease)
        lethality = disease(j);
        
        fprintf(...
            '\n\nherdlab(%i, %03i, %03i, %i, %i, %.2f, %i, %i, %i);\n',...
            env_size,...
            vuln_count,...
            vacc_count,...
            infec_count,...
            step_count,...
            lethality,...
            plot_control,...
            quick_stop,...
            img_output...
            );
        
        herdlab(env_size,...
            vuln_count,...
            vacc_count,...
            infec_count,...
            step_count,...
            lethality,...
            plot_control,...
            quick_stop,...
            img_output...
            );
    end
end
end

